resources:
  - name: repo_demo
    type: GitRepo
    configuration:
      gitProvider: ornaishtat_tests
      path: ornaishtattests/pipelinesdemo

pipelines:
  - name: demoPipelinesTEST
    steps:
      - name: demoStep_1
        type: Bash
        execution:
          onStart:
            - echo "Start message!"
          onExecute:
            - echo "Hello world!!"
          onComplete:
            - echo "Completed! does not mean success of failure but only that it's completed!"

